### ISSUE TITLE
Can't download library using CocoaPods 

### ISSUE THREAD

**Issue by grantkemp** [IngmarStein/FabricOSX#3]
I seem to get the following error when trying to install the Cocoapods: 

> Analyzing dependencies
> [!] Unable to satisfy the following requirements:
> - `Fabric/Crashlytics (~> 1.2.6)` required by `Podfile`
>   Dregir:Ecommerce Tools gkemp$ gem install cocoapods

I tried adding the Cocoapods for FabricOSX as well but it gives the following error

> [!] Unable to find a specification for `FabricOSX (~> 1.2)`

Any Idea?

**Comment by IngmarStein** [comment]
This pod is obsolete, please use Fabric now (https://cocoapods.org/pods/Fabric)
